### ISSUE TITLE
Feature request: rename mount/unmount commands to attach/detach

### ISSUE THREAD

**Issue by johanburati** [khenidak/dysk#17]
IMHO it would be better to change the mount/unmount commands to attach/detach.
It would make more sense since we are attaching/detaching a device and it would be similar to the azure cli command to attach disks.

```
Usage:                                                        |
  dyskctl [command]                                           | az vm disk

Available Commands:                                           | 
  create      creates a page blob but does not mount it       |
  get         gets a dysk (mounted on the local host) by name |
  help        Help about any command                          |
  list        lists all dysks mounted on local host           |
  mount       mounts a page blob as block device              | attach: Attach a managed persistent disk to a VM.
  mount-file  mounts a page blob as block device based on a j |
  unmount     unmount a dysk on the local machine             | detach: Detach a managed disk from a VM.
```

**Comment by khenidak** [comment]
I have been self debating this for a while now. In a lot ways we are not "attaching" disks. Because 

1. Attach requires **detach** before attaching the same disk some where else, while dysk does not need that. 
2. Aligning with Kubernetes terms. When a volume driver declare itself as "attach/detach" you won't be able to move disks around if the node is down (because kubelet has to perfrom the detach). While dysk does not do that

Check [design] https://github.com/khenidak/dysk/blob/master/docs/design.md *cluster split brain handling part. Let me know if i can improve it (or you can improve it :-))

in all cases, if the majority voted "attach" instead of "mount" i will just rename it
