### ISSUE TITLE
dysk.ko will be removed if dyskctl unmount all disks

### ISSUE THREAD

**Issue by andyzhangx** [khenidak/dysk#7]
How to repro:
1. Install dysk.ko module
2. dyskctl mount auto-create a disk
3. dyskctl unmount -d DISK-NAME
4. use below command to check, nothing will display
`lsmod | grep dysk`

```
$ uname -a
Linux k8s-linuxpool1-77890142-0 4.11.0-1016-azure #16-Ubuntu SMP Tue Dec 5 22:52:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

And my VM is even hung for a while when `dyskctl unmount` the last disk

**Comment by andyzhangx** [comment]
it happend again, when do `dyskctl unmount`, dysk.ko will be removed and then ssh connection lost

**Comment by khenidak** [comment]
Yes - Should have a fix out today. Thank you for following up

**Comment by khenidak** [comment]
Fixed with w/

- https://github.com/khenidak/dysk/commit/c19fa593f5a70d9a83c1e39f4c558ca75997918a
- https://github.com/khenidak/dysk/commit/e62070109db340d2ef13081372349c638df617e0

There was a crash because 1) the calculation of partition allocated for dysks were correct (upon mounting) 2) while unmounting the order of del/put calls was not correct

@ritazh This fixes the same issue you highlighted re unmounting as well. 

- Here are the tests i did (i am writing some scripts to CI/verify these things)
- Create/Mount many .. **OK**
- unmount many in order then remount .. **OK** 
- unmount in random order then remount.. **OK**
- mount, format, unmount, remount .. **OK**

**Comment by khenidak** [comment]
I am re-opening the issue because i noticed its re-occurrence randomly. Will investigate

**Comment by khenidak** [comment]
@ritazh @andyzhangx 

Ok, so i have fixed this (there was a wrong kfree(...) during connection_pool_teardown. This is a nasty bug because it affects further remounts (or new mounts)

I have also add aggressive mounts/remounts verification scripts. Check https://github.com/khenidak/dysk/tree/master/tools/verification
